---
- name: Build PostgreSQL Docker Image
  hosts: "{{ target_hosts | default('none') }}"
  become: true
  vars:
    ansible_user: "{{ lookup('ansible.builtin.config', 'DEFAULT_REMOTE_USER') }}"
    postgres_src_dir: "/tmp/{{ ansible_user }}/{{ project_name }}/pgsql/"
    docker_image_name: "{{ project_name }}-postgresql:{{ postgres_version }}"
    docker_image_tag: "{{ postgres_version }}"
  vars_files:
    - "../vars/secrets.yml"
    - "../vars/main.yml"
  tasks:
    - name: Ensure host install directory exists
      ansible.builtin.file:
        path: "{{ postgres_src_dir }}"
        state: directory
        mode: '0755'
      become_user: "{{ ansible_user }}"

    - name: Copy entrypoint
      template:
        src: ../templates/entrypoint.sh.j2
        dest: "{{ postgres_src_dir }}/entrypoint.sh"
        mode: '644'
      become_user: "{{ ansible_user }}"

    - name: Create Dockerfile
      template:
        src: ../templates/postgres-Dockerfile.j2
        dest: "{{ postgres_src_dir }}/Dockerfile"
      become_user: "{{ ansible_user }}"

    - name: Build Postgres "{{ postgres_version }}" Image
      community.docker.docker_image:
        name: "{{ docker_image_name }}"
        tag: "{{ docker_image_tag }}"
        build:
          path: "{{ postgres_src_dir }}"
          dockerfile: Dockerfile
        source: build

    - name: Removal of Postgres source folder
      ansible.builtin.file:
        path: "{{ postgres_src_dir }}"
        state: absent
