---
- hosts: "{{ target_hosts | default('none') }}"
  gather_facts: false
  become: true
  vars:
    ansible_user: "{{ lookup('ansible.builtin.config', 'DEFAULT_REMOTE_USER') }}"    
    docker_network: "{{ project_name }}_default"
    project_dir: "/tmp/{{ ansible_user }}/{{ project_name }}"
    docker_compose_src: '../templates/compose.yml.j2'
  vars_files:
    - "../vars/secrets.yml"
    - "../vars/main.yml"

  tasks:
  - name: Check if Docker Compose is installed
    command: docker compose --version
    register: docker_compose_installed
    failed_when: docker_compose_installed.rc != 0
    changed_when: false

  - assert:
      that: docker_compose_installed.rc == 0
  
  - name: Set up Docker Compose environment variables
    set_fact:
      docker_compose_env:
        Keycloak_database_user: "{{ keycloak_database_user }}"
        Keycloak_database_name: "{{ keycloak_database_name }}" 
        Keycloak_database_password: "{{ keycloak_database_password }}"

  - name: Run docker-compose up
    community.docker.docker_compose_v2:
      project_name: "{{ project_name }}"
      state: present # or 'present'
      definition: "{{ lookup('template', docker_compose_src ) | from_yaml }}"

  - name: "get network info"
    community.docker.docker_network_info:
      name: "{{ docker_network }}"
    register: net_info

  - name: "check availability of network"
    assert: 
      that: net_info.network | length > 0
      fail_msg: "Docker network '{{ docker_network }}' not found."

  - name: "get container keys"
    set_fact:
      container_info_keys: "{{ net_info.network.Containers.keys() }}"

  - name: "get container info"
    set_fact: 
      container_info: "{{ net_info.network.Containers.values() }}"

  - name: list container names
    set_fact:
      list_running_containers: "{{ container_info | map(attribute='Name') | list }}"
    when: container_info is defined

  - name: Display available containers (using the fact)
    debug:
      msg: "Available Docker containers on {{ inventory_hostname }} : {{ list_running_containers | list }}"
    when: list_running_containers is defined and list_running_containers | length > 0

  - name: Display available containers keys (using the fact)
    debug:
      msg: "Available Docker containers on {{ inventory_hostname }} : {{ container_info_keys | list }}"
    when: container_info_keys is defined and container_info_keys | length > 0
